"""add a new column to branch table

Revision ID: 052490300714
Revises: a3363db0a393
Create Date: 2024-07-09 14:24:58.207384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '052490300714'
down_revision: Union[str, None] = 'a3363db0a393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'branches', 'users', ['manager_id'], ['id'])
    op.alter_column('users', 'user_type',
               existing_type=mysql.TINYINT(),
               comment='1.super_admin,2.admin,3.customer,4.manager',
               existing_comment='1.super_admin,2.admin,3.customer',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type',
               existing_type=mysql.TINYINT(),
               comment='1.super_admin,2.admin,3.customer',
               existing_comment='1.super_admin,2.admin,3.customer,4.manager',
               existing_nullable=True)
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_column('branches', 'manager_id')
    # ### end Alembic commands ###
