"""add a column vehicle_added_at in vehicledetail table

Revision ID: 096b1824bfb5
Revises: 0bb3431947c0
Create Date: 2024-07-03 16:46:52.006271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096b1824bfb5'
down_revision: Union[str, None] = '0bb3431947c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_details', sa.Column('vehicle_added_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_details', 'vehicle_added_at')
    # ### end Alembic commands ###
