"""add password column to user table

Revision ID: 2f6311198f02
Revises: 77667da777e8
Create Date: 2024-07-02 17:45:31.040355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2f6311198f02'
down_revision: Union[str, None] = '77667da777e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=True))
    op.alter_column('users', 'user_type',
               existing_type=mysql.TINYINT(),
               comment='1.super_admin,2.admin,3.customer',
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=mysql.TINYINT(),
               comment='0.Delete,1.Active,-1.Inactive',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=mysql.TINYINT(),
               comment=None,
               existing_comment='0.Delete,1.Active,-1.Inactive',
               existing_nullable=True)
    op.alter_column('users', 'user_type',
               existing_type=mysql.TINYINT(),
               comment=None,
               existing_comment='1.super_admin,2.admin,3.customer',
               existing_nullable=True)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
