"""change the column name in branch table

Revision ID: 336442ff8d3a
Revises: be6bc4dcafa5
Create Date: 2024-07-08 09:18:12.273105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '336442ff8d3a'
down_revision: Union[str, None] = 'be6bc4dcafa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('approved_status', mysql.TINYINT(), nullable=True, comment='1.Approved, -1.Pending'))
    op.drop_column('branches', 'pending_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('pending_status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1.Approved, -1.Pending'))
    op.drop_column('branches', 'approved_status')
    # ### end Alembic commands ###
