"""remove the relation between the bookedvehicle and pricedetail

Revision ID: 37b4b72999c6
Revises: d0471a1a6443
Create Date: 2024-07-04 15:11:47.794539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37b4b72999c6'
down_revision: Union[str, None] = 'd0471a1a6443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booked_vehicles_ibfk_2', 'booked_vehicles', type_='foreignkey')
    op.drop_column('booked_vehicles', 'price_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booked_vehicles', sa.Column('price_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('booked_vehicles_ibfk_2', 'booked_vehicles', 'price_details', ['price_id'], ['id'])
    # ### end Alembic commands ###
