"""add a new table name price ranges

Revision ID: 47791ff27fc1
Revises: e2baacb2582c
Create Date: 2024-07-04 09:37:10.121377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47791ff27fc1'
down_revision: Union[str, None] = 'e2baacb2582c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priceranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('range', sa.String(length=15), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('price_details', sa.Column('price_range_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'price_details', 'priceranges', ['price_range_id'], ['id'])
    op.drop_column('price_details', 'time_range')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_details', sa.Column('time_range', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'price_details', type_='foreignkey')
    op.drop_column('price_details', 'price_range_id')
    op.drop_table('priceranges')
    # ### end Alembic commands ###
