"""create a new column in booked vehicle

Revision ID: 587fa5dec1e7
Revises: 9b7b815dcf1d
Create Date: 2024-07-10 17:32:43.017845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587fa5dec1e7'
down_revision: Union[str, None] = '9b7b815dcf1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
