"""create the tables

Revision ID: 77667da777e8
Revises: b9595ba6b47b
Create Date: 2024-07-02 15:21:16.599531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '77667da777e8'
down_revision: Union[str, None] = 'b9595ba6b47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_names', sa.String(length=60), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('e_mail', sa.String(length=50), nullable=True),
    sa.Column('ph_no', sa.String(length=10), nullable=True),
    sa.Column('user_type', mysql.TINYINT(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=15), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=60), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_range', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_no', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booked_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('from_time', sa.DateTime(), nullable=True),
    sa.Column('to_time', sa.DateTime(), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('booked_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['price_details.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booked_vehicles')
    op.drop_table('vehicle_details')
    op.drop_table('price_details')
    op.drop_table('branches')
    op.drop_table('vehicle_types')
    op.drop_table('users')
    op.drop_table('districts')
    # ### end Alembic commands ###
