"""change plural to singular column name in district table

Revision ID: 809cb870917e
Revises: a0535bea95a7
Create Date: 2024-07-03 10:04:33.229267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '809cb870917e'
down_revision: Union[str, None] = 'a0535bea95a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('district_name', sa.String(length=60), nullable=True))
    op.drop_column('districts', 'district_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('district_names', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('districts', 'district_name')
    # ### end Alembic commands ###
