"""add a new column created_at in parkingstation

Revision ID: 9a1618eec2a1
Revises: 326b83ed97ec
Create Date: 2024-07-04 16:17:54.765064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1618eec2a1'
down_revision: Union[str, None] = '326b83ed97ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_stations', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_stations', 'created_at')
    # ### end Alembic commands ###
