"""create a new column in booked vehicle table

Revision ID: 9e8d39880c16
Revises: 587fa5dec1e7
Create Date: 2024-07-10 17:35:14.443069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8d39880c16'
down_revision: Union[str, None] = '587fa5dec1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booked_vehicles', sa.Column('district_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booked_vehicles', 'districts', ['district_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booked_vehicles', type_='foreignkey')
    op.drop_column('booked_vehicles', 'district_id')
    # ### end Alembic commands ###
