"""add comment to branch table

Revision ID: a0535bea95a7
Revises: 2f6311198f02
Create Date: 2024-07-03 08:57:30.738519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a0535bea95a7'
down_revision: Union[str, None] = '2f6311198f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branches', 'district_id',
               existing_type=mysql.INTEGER(),
               comment='refered districts',
               existing_nullable=True)
    op.add_column('users', sa.Column('pass_word', sa.String(length=100), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('users', 'pass_word')
    op.alter_column('branches', 'district_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='refered districts',
               existing_nullable=True)
    # ### end Alembic commands ###
