"""add a status comment in Bookedvehicle table

Revision ID: a3363db0a393
Revises: 679e48917c38
Create Date: 2024-07-08 17:00:27.465038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3363db0a393'
down_revision: Union[str, None] = '679e48917c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booked_vehicles', 'status',
               existing_type=mysql.TINYINT(),
               comment='0.Cancelled, 1.Active, -1.Inactive',
               existing_comment='1.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booked_vehicles', 'status',
               existing_type=mysql.TINYINT(),
               comment='1.',
               existing_comment='0.Cancelled, 1.Active, -1.Inactive',
               existing_nullable=True)
    # ### end Alembic commands ###
