"""add a new column to branch table

Revision ID: be6bc4dcafa5
Revises: 5aaae1ee0147
Create Date: 2024-07-08 09:08:46.379806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be6bc4dcafa5'
down_revision: Union[str, None] = '5aaae1ee0147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('pending_status', mysql.TINYINT(), nullable=True, comment='1.Approved, -1.Pending'))
    op.alter_column('branches', 'status',
               existing_type=mysql.TINYINT(),
               comment='0.Deleted,1.Active,-1.Inactive',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branches', 'status',
               existing_type=mysql.TINYINT(),
               comment=None,
               existing_comment='0.Deleted,1.Active,-1.Inactive',
               existing_nullable=True)
    op.drop_column('branches', 'pending_status')
    # ### end Alembic commands ###
