"""modify the manager table

Revision ID: bf423a24e078
Revises: 9e8d39880c16
Create Date: 2024-07-11 11:44:31.673209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf423a24e078'
down_revision: Union[str, None] = '9e8d39880c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managers', 'status',
               existing_type=mysql.TINYINT(),
               comment='1-Active, -1-Inactive',
               existing_comment='0-Delete, 1-Active, -1-Inactive',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managers', 'status',
               existing_type=mysql.TINYINT(),
               comment='0-Delete, 1-Active, -1-Inactive',
               existing_comment='1-Active, -1-Inactive',
               existing_nullable=True)
    # ### end Alembic commands ###
