"""changes made in multiple tables

Revision ID: c8c9b8f05658
Revises: 6dfe945551d7
Create Date: 2024-07-06 17:05:22.583964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c8c9b8f05658'
down_revision: Union[str, None] = '6dfe945551d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booked_vehicles', 'booked_price',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('booked_vehicles', 'status',
               existing_type=mysql.TINYINT(),
               comment='1.',
               existing_nullable=True)
    op.add_column('districts', sa.Column('pending_status', mysql.TINYINT(), nullable=True, comment='1.Approved,-1.Pending,'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('districts', 'pending_status')
    op.alter_column('booked_vehicles', 'status',
               existing_type=mysql.TINYINT(),
               comment=None,
               existing_comment='1.',
               existing_nullable=True)
    op.alter_column('booked_vehicles', 'booked_price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
