"""change a string length of column vehicle_no in vehicle_details table

Revision ID: e2baacb2582c
Revises: 096b1824bfb5
Create Date: 2024-07-03 17:47:58.816406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2baacb2582c'
down_revision: Union[str, None] = '096b1824bfb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_details', 'vehicle_no',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_details', 'vehicle_no',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
