"""add a comment to status column in district table

Revision ID: e443950973df
Revises: 7a5baa81da32
Create Date: 2024-07-03 12:48:51.113402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e443950973df'
down_revision: Union[str, None] = '7a5baa81da32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('districts', 'status',
               existing_type=mysql.TINYINT(),
               comment='0.Delete,1.Active,-1.Inactive',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('districts', 'status',
               existing_type=mysql.TINYINT(),
               comment=None,
               existing_comment='0.Delete,1.Active,-1.Inactive',
               existing_nullable=True)
    # ### end Alembic commands ###
